[package]
name = "context_server"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/context_server.rs"

[features]
default = ["rmcp"]
test-support = []
# Feature for RMCP SDK migration
rmcp = ["dep:rmcp", "dep:tokio"]

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
collections.workspace = true
futures.workspace = true
gpui.workspace = true
log.workspace = true
net.workspace = true
parking_lot.workspace = true
postage.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
smol.workspace = true
tempfile.workspace = true
url = { workspace = true, features = ["serde"] }
util.workspace = true
workspace-hack.workspace = true

# RMCP SDK - the actual crate from crates.io
# Additional dependencies needed when using RMCP
tokio = { workspace = true, optional = true }
rand = { workspace = true }
settings = { workspace = true }
settings_ui_macros = { workspace = true }
reqwest = { version = "0.11.27", features = ["json"] }
rmcp = { version = "0.6.2", optional = true, features = [
    "client",
    "transport-sse-client-reqwest",
    "reqwest",
    "transport-streamable-http-client-reqwest",
    "transport-child-process",
    "tower"
] }
